program: train_third.py
method: bayes
metric: 
  goal: maximize
  name: ariel_score
parameters:
  H1:
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  H2: 
    values: [64, 128, 256, 512, 1024]
  H3: 
    values: [4, 8, 16, 32, 64, 128, 256, 512, 1024]
  D1: 
    min: 0.01
    max: 0.5
  mean: 
    values: [0.0, 1.0]
  std: 
    min: 0.005
    max: 0.5
  lr: 
    values: [0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03, 0.1, 0.3]
  batch_size:
    values: [10, 25, 50, 100]
early_terminate:
  type: hyperband
  max_iter: 27
  s: 2
  eta: 3